version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Good for debugging the DB from your host machine
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend_/Dockerfile
    container_name: burger-house-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/burgerdb
    depends_on:
      - mongo

volumes:
  mongo_data: