apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: abhinay9876/burger-house-frontend:latest # <-- ⚠️ REPLACE with your Docker Hub username
        imagePullPolicy: Never # <-- Use the same local image trick
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # This exposes the service outside the cluster
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # The port the service will listen on
      targetPort: 80  # The port on the Nginx container