name: CI Build Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: backend_/Dockerfile
          push: false
          tags: burger-house-backend:latest

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend_
          dockerfile: ./frontend_/Dockerfile
          push: false
          tags: burger-house-frontend:latest